version: '3'

services:
  godo:
    build: .
    container_name: godo
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - godo-postgres
    links:
      - godo-postgres

  godo-postgres:
    image: postgres:12
    container_name: godo-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
