version: '3'

services:
  godo:
    build: .
    container_name: godo
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=postgres

  db:
    image: postgres:12
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
